server:
  port: 9090

spring:
  application:
    name: admin-server
  main:
    allow-bean-definition-overriding: true

  #Mail configuration
  mail:
    host: smtp.mailtrap.io
    port: 2525
    username: ce10f8fcc34335
    password: f9343bf10c0bcc
    test-connection: true
  boot:
    admin:
      notify:
        mail:
          to:
            - admi@gmail.com
            - issus_onlieportal@gmail.com
      ui:
        title: 'ADMIN SERVER'
        favicon: 'assets/img/favicon.jpg'
        favicon-danger: 'assets/img/favicon-danger.jpg'
        login-icon: 'assets/img/logo.jpg
        available-languages:
          - en
          - zh
        view-settings:
          - name: 'about'
            enabled: false