server:
  port: 9091

spring:
  application:
    name: product-microservice
  profiles:
    active: dev
  data:
    mongodb:
      host: localhost
      port: 27017
      database: test

logging:
  file:
    name: d:\logs\product.log
    path: d:\logs #spring.log default log file name
  logback:
    rollingpolicy:
      max-file-size: 20KB

#Actuator specific configuration
management:
  endpoints:
    web:
      exposure:
        include:
          - '*'
  endpoint:
    health:
      show-details: ALWAYS

info:
  app:
    name: Product Microservice
    version: 1.0
    description: crud operation for product

product:
  currencies:
    - SGD
    - AUD

#update few configurations without creating new file
---
spring:
  config:
    active:
      on-profile:
        - stg

server:
  port: 9099

product:
  currencies:
    - AUD